### ISSUE TITLE
Day 1 Plan

### ISSUE THREAD

**Issue by anandology** [amitkaps/mlops#4]
## Todos

**Anand**
- [x] cookie cutter
- [x] data validation using pandera
- [ ] add unittests in penguins-level2
- [ ] slide for devops vs. mlops comparison

**Amit**
- [ ] Complete Day 1 docs
- [ ] create level2 diamons and keep in a branch
